# This image extends service-manager:base and adds the Lapps services running
# on the Vassar node.

FROM ksuderman/service-manager:base

USER root
ADD ./packages/lappsgrid-gate.tgz /usr/share/gate
ADD ./packages/lappsgrid-models.tgz /usr/share/lapps
ADD ./packages/MASC-3.0.0.tgz /var/corpora/MASC-3.0.0
ADD ./packages/lappsgrid-services.tgz /usr/share/tomcat/service-manager/webapps
ADD ./packages/lddl-scripts.tgz /etc/lddl

ADD ./startup-vassar.sh /usr/bin/startup

CMD ["/usr/bin/startup"]
