# A Lappsgrid Service Manager with the GATE and Stanford services installed.

FROM ksuderman/ubuntu

MAINTAINER Keith Suderman, suderman@cs.vassar.edu

#RUN echo "192.168.99.100		docker" >> /etc/hosts

# Install tomcat to /usr/share
COPY ./packages/tomcat.tgz /usr/share/tomcat

# Call our startup script when the container starts.
CMD [ "/usr/bin/startup" ]



