# This image extends service-manager:base and adds the Lapps services running
# on the Brandeis node.

FROM ksuderman/service-manager:base

USER root
ADD ./packages/brandeis-services.tgz /usr/share/tomcat/service-manager/webapps
ADD ./packages/lddl-scripts.tgz /etc/lddl

ADD ./startup-brandeis.sh /usr/bin/startup

CMD ["/usr/bin/startup"]
